version: '3.8'

services:
  restapiservice:
    build:
      context: .
      dockerfile: docker/RESTApiService.Dockerfile
    ports:
      - "5290:5290"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - postgresdb

  messageclientapp:
    build:
      context: .
      dockerfile: docker/MessageClientApp.Dockerfile
    ports:
      - "5240:5240"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - restapiservice
      - postgresdb

  postgresdb:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
